version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "MoonMoon1919/reloader"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building test Docker Image"
    type: "build"
    image_name: "MoonMoon1919/reloader"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  run_all_checks:
    type: "parallel"
    stage: "test"
    steps:
      run_tests:
        title: "Run PyTest"
        image: "${{build}}"
        commands:
          - "make test"
        stage: "test"
      run_safety:
        title: "Run Safety"
        image: "${{build}}"
        commands:
          - "make check/safety"
      run_format_check:
        title: "Run Formatting Check"
        image: "${{build}}"
        commands:
          - "make check/format"
    when:
      condition:
        all:
          noSkipCiInCommitMessage: 'includes(lower("${{CF_COMMIT_MESSAGE}}"), "skip ci") == false'
